name: CI

on: push

env:
  ANDROID_NDK_VERSION: r25b
  NODE_TARGETS_DEFAULT: '12.0.0 14.0.0 16.0.0 18.0.0 19.0.0'
  NODE_TARGETS_FREEBSD: '14.0.0 16.0.0 17.0.1'
  ELECTRON_TARGETS_DEFAULT: '21.0.0'
  ELECTRON_TARGETS_FREEBSD: '16.0.0'

jobs:
  frida-linux:
    strategy:
      matrix:
        arch: [x86_64]
      fail-fast: false
    runs-on: ubuntu-latest
    container: ghcr.io/frida/x-tools-linux-${{ matrix.arch }}:latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - name: Install packages needed for installing Qt
        if: matrix.arch == 'x86_64'
        run: |
          apt-get update
          apt-get install -y sudo
      - name: Test Qt ricky
        if: matrix.arch == 'x86_64'
        uses: 1217279512/nimasile@v3
        with:
          cache: true
          setup-python: false
